name: CI/CD

on:
  push:
  pull_request:

env:
  NODE_VERSION: 16.x
  AWS_REGION : "eu-west-1"

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: noi-techpark/github-actions/checkout@v2

      - uses: noi-techpark/github-actions/yarn-build@v2


  deploy-test:
    runs-on: ubuntu-20.04
    if: github.ref == 'refs/heads/main'
    needs: test
    concurrency: deploy-test
    env:
      AWS_S3_BUCKET_NAME : 'com.opendatahub.parking-test'
    steps:
      - uses: noi-techpark/github-actions/checkout@v2

      - uses: noi-techpark/github-actions/yarn-build@v2
        with:
          build-command: yarn generate

      - name: Sync to S3 bucket
        uses: noi-techpark/github-actions/aws-s3-bucket-sync@v2
        with:
          access-key-id: ${{ secrets.AWS_S3_ACCESS_KEY_ID }}
          secret-access-key: ${{ secrets.AWS_S3_SECRET_ACCESS_KEY }}
          region: ${{ env.AWS_REGION }}
          s3-bucket-name: ${{ env.AWS_S3_BUCKET_NAME }}
          folder: ./dist

  deploy-map-performance:
    runs-on: ubuntu-20.04
    if: github.ref == 'refs/heads/map-performance'
    needs: test
    concurrency: deploy-map-performance
    env:
      AWS_S3_BUCKET_NAME : 'com.opendatahub.parking-test-2'
    steps:
      - uses: noi-techpark/github-actions/checkout@v2

      - uses: noi-techpark/github-actions/yarn-build@v2
        with:
          build-command: yarn generate

      - name: Sync to S3 bucket
        uses: noi-techpark/github-actions/aws-s3-bucket-sync@v2
        with:
          access-key-id: ${{ secrets.AWS_S3_ACCESS_KEY_ID }}
          secret-access-key: ${{ secrets.AWS_S3_SECRET_ACCESS_KEY }}
          region: ${{ env.AWS_REGION }}
          s3-bucket-name: ${{ env.AWS_S3_BUCKET_NAME }}
          folder: ./dist

  # deploy-prod:
  #   runs-on: ubuntu-20.04
  #   if: github.ref == 'refs/heads/prod'
  #   needs: test
  #   concurrency: deploy-prod
  #   env:
  #     AWS_S3_BUCKET_NAME : 'com.opendatahub.parking-prod'
  #   steps:
  #     - uses: noi-techpark/github-actions/checkout@v2

  #    - uses: noi-techpark/github-actions/yarn-build@v2
  #      with:
  #        build-command: yarn generate

  #    - name: Sync to S3 bucket
  #      uses: noi-techpark/github-actions/aws-s3-bucket-sync@v2
  #      with:
  #        access-key-id: ${{ secrets.AWS_S3_ACCESS_KEY_ID }}
  #        secret-access-key: ${{ secrets.AWS_S3_SECRET_ACCESS_KEY }}
  #        region: ${{ env.AWS_REGION }}
  #        s3-bucket-name: ${{ env.AWS_S3_BUCKET_NAME }}
  #        folder: ./dist
